### ISSUE TITLE
Add EXIF data instead of log file?

### ISSUE THREAD

**Issue by mgrhm** [romainmenke/simple-guetzli#5]
There's an [issue for `guetzli`](https://github.com/google/guetzli/issues/141) suggesting the use of an EXIF comment to track whether an image has already been compressed by `guetzli`.

Even if this isn't accepted into the main `guetzli`, this would be a great addition for `simple-guetzli`.  It would remove the dependency on a single, separate log file.

**Comment by romainmenke** [comment]
Seems of very limited use to me as the intended goal of Guetzli is to reduce the file size of images served over the internet without reducing the perceived quality. Including EXIF data increases the file size.

The log file does not store info about the processed image. It stores info about the original image. This is intentional and changing this would break this tool.
